doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Product:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Plugins/Product/Entity'
                prefix: 'App\Plugins\Product\Entity'
                alias: Product
            Marketing:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Plugins/Marketing/Entity'
                prefix: 'App\Plugins\Marketing\Entity'
                alias: Marketing
            Log:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Plugins/Log/Entity'
                prefix: 'App\Plugins\Log\Entity'
                alias: Log
#            App:
#                is_bundle: false
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App


when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
